### ISSUE TITLE
请问为什么连不上代理

### ISSUE THREAD

**Issue by firstwaterer** [ygkkk/EUservWARP#1]
测试过了
用你的wgcf和我自己手动bash的warp
可以curl ip.gs可以下载文件 但是为什么xray或v2ray测试延迟会有错误，要不要在cloudflare上设置什么
我重装过两次系统

**Comment by ygkkk** [comment]
> 测试过了
> 用你的wgcf和我自己手动bash的warp
> 可以curl ip.gs可以下载文件 但是为什么xray或v2ray测试延迟会有错误，要不要在cloudflare上设置什么
> 我重装过两次系统

用ws自选ip试试

**Comment by firstwaterer** [comment]
有没有数字海洋的ip

甬哥侃侃侃 ***@***.***> 于2021年8月31日周二 下午7:36写道：

**Comment by firstwaterer** [comment]
为什么这么慢

**Comment by ygkkk** [comment]
> 为什么这么慢

正常
